# Generated by Django 3.0.1 on 2020-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sid', models.IntegerField()),
                ('smarks', models.IntegerField()),
                ('sclass', models.CharField(max_length=20)),
            ],
        ),
    ]
