# Generated by Django 3.0.1 on 2020-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=15)),
                ('pages', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
